version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: idealmeter_app:latest
        container_name: idealmeter_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
        environment:
            COMPOSER_ALLOW_SUPERUSER: "1"
        depends_on:
            - db
        networks:
            - idealmeter

    web:
        image: nginx:1.25-alpine
        container_name: idealmeter_web
        depends_on:
            - app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - idealmeter

    db:
        image: postgres:15-alpine
        container_name: idealmeter_db
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        networks:
            - idealmeter

volumes:
    pgdata:

networks:
    idealmeter:
        driver: bridge
